kind: Deployment
apiVersion: apps/v1
metadata:
  name: metuaa-admin-mapper
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metuaa-admin-mapper
  template:
    metadata:
      labels:
        app: metuaa-admin-mapper
    spec:
      containers:
        - name: metuaa-admin-mapper
          image: dpaved/metuaa-admin-mapper:1.0

          imagePullPolicy: Always
          ports:
            - containerPort: 80
